DATETIME_FORMATE_CODE = "%d-%m-%Y"
ANALYSIS_JOB_CREATION_DAILY_LIMIT = 5
PANDAS_DF_DATE_FORMATE_CODE = "%Y-%m-%d"
DEFAULT_TARGET_PE_RATIO = 25
VALID_CURRENCIES = {"USD", "GBP", "EUR", "JPY", "CAD", "AUD", "HKD"}
