name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: open-source-apps-001
  IMAGE: python-fear-greed-api
  REGISTRY_HOSTNAME: gcr.io
  CLOUD_RUN_SERVICE: python-fear-greed-api

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.11]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Cloud SDK
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Linting
        run: |
          flake8
      - name: Run unit tests
        env:
          TEST_USER_PASSWORD: "${{ secrets.TEST_USER_PASSWORD }}"
          MONGO_DB_CONNECTION_STRING: "${{ secrets.MONGO_DB_CONNECTION_STRING }}"
          JWT_SECRET: "${{ secrets.JWT_SECRET }}"
        run: |
          python -m pytest tests
          python -m pytest --cov=api
  setup-build-publish-deploy:
    needs: test
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: Authenticate with Container Registry
        run: |
          gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: Build
        run: |-
          docker build -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" -t \
          "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:latest" .
      # Push the Docker image to Google Container Registry
      - name: Push
        run: |
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" 
          docker push "$REGISTRY_HOSTNAME"/$PROJECT_ID/"$IMAGE":latest
      - name: Deploy
        run: |
          gcloud run deploy ${CLOUD_RUN_SERVICE} --image "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE:$GITHUB_SHA" --region europe-west1 \
          --update-secrets=MONGO_DB_CONNECTION_STRING=python-scraper-mongo-db-connection-string:latest\
          ,JWT_SECRET=jwt-secret:latest,OAUTH_CLIENT_ID=oauth-client-id:latest
